[package]
name = "tecexp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
form_urlencoded = "1.2.1"
notify = "6.1.1"
time = { version = "0.3.36", features = ["formatting"] }
